name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
# TW-NOTE: Specific specific branch if needed
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        # TW-NOTE: skipping tests as we are having timeout starting postgres via testcontainers
        # Needs to be fixed
        run: ./mvnw --no-transfer-progress verify -DskipTests

      - if: github.ref == 'refs/heads/main'
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: github.ref == 'refs/heads/main'
        name: Build and Publish Docker Image
        run: |
          ./mvnw spring-boot:build-image -DskipTests
          docker push ${{ vars.DOCKERHUB_USERNAME }}/bookstore-catalog-service


