name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
# TW-NOTE: Specific specific branch if needed
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21.0.6+7'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw --no-transfer-progress verify